# pacman.conf used while BUILDING the ISO. Not the one that ends up installed.
[options]
HoldPkg      = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 8
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
